### PR TITLE
Upgrade to TLS-Attacker 4.0.2

### PR DESCRIPTION
**Pull request by kostis**

### CODE REVIEW

**Comment by pfg666** [comment]
The cause appears to be a renaming of variables in TLS-Attacker. I updated the alphabet files in 'examples' to be consistent with the renaming. Note, there are alphabet files in the 'results' folder which still use the outdated variable name (certificateListConfig) instead of the new name (certificatesListConfig). I did not change those (we normally do not use these alphabet files in experiments, they are just there for logging purposes).

**Comment by kostis** [comment]
All the tests now pass.  Perhaps it is a good idea to leave a comment describing what the "alternative fix" entails and why the previous code did not work, and then this PR can be merged.

**Comment by pfg666** [comment]
The original fix unfortunately did not have the desired effect. The renamed variable, used to make the Certificate empty, was ignored by TLS-Attacker, which resulted in the Certificate generated being a regular Certificate. The fix now defines a class for defining Certificate inputs. This eases specification of the inputs. Before they are defined using GenericTlsInput, which meant we had to specify the contents of the Certificate (and had to deal with variable renaming). 
It is best to have specialized classed for all the common (D)TLS messages.

**Comment by kostis** [comment]
Looks good. Thanks @pfg666 !  I will merge this.

**Pull request merged**
